pipeline:

  build:
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:latest
    commands:
      - /root/entrypoint.sh
      - sbt test yarnInstall buildReactApp docker:stage
    environment:
      - ARTIFACTORY_USERNAME=drt_artifactory
    secrets:
      - ARTIFACTORY_PASSWORD
      - PG_DATABASE_HOST
      - PG_DATABASE_PORT
      - PG_DATABASE_USERNAME
      - PG_DATABASE_PASSWORD
      - PG_DATABASE
      - PORT_CODES
    when:
      event:
        - push

  build_push_to_ecr:
    image: quay.io/ukhomeofficedigital/ecr:latest
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    repo: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/drt/drt-iei-dashboard
    build_args:
      - APP_BUILD=${DRONE_COMMIT_SHA}
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_BUILD_NUMBER}
    when:
      event:
        - push
